default_language_version:
  python: python3.12

repos:
  - repo: https://github.com/python-poetry/poetry
    rev: 1.8.4
    hooks:
      - id: poetry-check

  - repo: https://github.com/asottile/pyupgrade
    rev: v3.18.0
    hooks:
      - id: pyupgrade
        args: [--py37-plus, --keep-runtime-typing]

  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.6.9
    hooks:
      - id: ruff
        args: [--fix]
      - id: ruff-format

  - repo: https://github.com/PyCQA/bandit
    rev: 1.7.10
    hooks:
      - id: bandit
        args: [-ll, .]

  - repo: local
    hooks:
      - id: poetry_install
        name: poetry-install
        entry: poetry install
        language: system
        pass_filenames: false

  - repo: https://github.com/RobertCraigie/pyright-python
    rev: v1.1.385
    hooks:
      - id: pyright
        entry: poetry run pyright

  - repo: "https://github.com/trufflesecurity/trufflehog"
    rev: "v3.88.14"
    hooks:
      - id: trufflehog
